### ISSUE TITLE
blobstore write access

### ISSUE THREAD

**Issue by ships** [cloudfoundry-community/nomad-boshrelease#1]
Hi friends

I have been using this release and want to make some modifications. currently maintaining my own fork & blobstore, but because of how blobstores work it is of course not entirely workable to just fork & PR.

Who owns/maintains the S3 bucket for this blobstore ? can I get write access to it ?

eve

**Comment by bodymindarts** [comment]
The blobs are stored on the cf-community owned s3 bucket. @drnic manages access.

**Comment by drnic** [comment]
Contact me via email drnicwilliams@gmail.com and I'll help set you up with
some credentials.

**Comment by ships** [comment]
this was resolved out-of-band. closing.
